name: move_pepper
args: []
kwargs: {}

dataset:
  _target_: "datasets.move_pepper_dset.load_move_pepper_slice_train_val"
  n_rollout: null
  normalize_action: ${normalize_action}
  data_path: ${oc.env:DATASET_DIR}/move_pepper
  split_ratio: 0.9
  transform:
    _target_: "datasets.img_transforms.default_transform"
    img_size: ${img_size}

decoder_path: null
num_workers: 16